title: Omer Sany Prakash
logo: images/cropped_profile_image.png
theme: jekyll-theme-minimal

# Add these new fields for the buttons
resume_url: files/Omer_Sany_Prakash_Resume.pdf  # Path to your resume file in assets folder
email: oprakash@missouri.edu  # Replace with your actual academic email

# Optional: You can also add these for more customization
show_downloads: false
google_analytics: # Your GA tracking ID if you have one

# Social links (optional)
github_username: omersany002
linkedin_username: Omer Sany Prakash
